### ISSUE TITLE
Notice: Undefined variable: userinfo 

### ISSUE THREAD

**Issue by burqka** [tholeb/tlb_police_web_panel#2]
Hey!

Just set up your website, but getting Notice error about undefined variable: userinfo when logged in. In every page where you can find `($userinfo{'role'} == 0)` etc, its giving out an error.

**Comment by tholeb** [comment]
Hi, i'm sorry for the delay. I made a mistake at every file containing `$userinfo`. 

**REPLACE THIS:**
`<?php
if(isset($_SESSION['id']) AND $_SESSION['id'] > 0) {
	 $getid = intval($_SESSION['id']);
	 $requser = $bdd->prepare('SELECT * FROM membres WHERE id = ?');
	 $requser->execute(array($getid));
	 $userinfo = $requser->fetch();
	 $ranguser = $bdd->query('SELECT * FROM membres(role) VALUES (?)');
	}
?>`

**TO:**

`<?php
  if(isset($_SESSION['steamid']) and $_SESSION['steamid'] > 0){
    $steamid = $_SESSION['steamid'];
    $query = $bdd->query("SELECT * FROM membres WHERE steamid = '$steamid';");
    $userinfo = $query->fetch();
  }
?>
`

Sorry for the error, I will realease another panel which is largely better and using material design.
[Version 3.0](https://prnt.sc/o28ebx)

**Comment by burqka** [comment]
That doesn't change anything.
